/*
Copyright © 2023 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
*/
// Code generated by go-swagger; DO NOT EDIT.

package provisionerclient

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/vmware/terraform-provider-tanzu-mission-control/internal/client/transport"
	"github.com/vmware/terraform-provider-tanzu-mission-control/internal/helper"
	provisioner "github.com/vmware/terraform-provider-tanzu-mission-control/internal/models/provisioner"
)

const (
	apiVersionAndGroup = "v1alpha1/managementclusters"

	queryParamKeyOrgID = "fullName.orgId"

	queryParamKeyProvisioners = "provisioners"
)

/*
Client for provisioner resource service API
*/
type Client struct {
	*transport.Client
}

func New(transport *transport.Client) ClientService {
	return &Client{Client: transport}
}

// ClientService is the interface for Client methods
type ClientService interface {
	ProvisionerResourceServiceCreate(request *provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerCreateProvisionerRequest) (*provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerCreateProvisionerResponse, error)

	ProvisionerResourceServiceDelete(params *provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerFullName) error

	ProvisionerResourceServiceGet(params *provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerFullName) (*provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerCreateProvisionerResponse, error)

	ProvisionerResourceServiceUpdate(params *provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerCreateProvisionerRequest) (*provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerCreateProvisionerResponse, error)

	ProvisionerResourceServiceList(params *provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerFullName) (*provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerListprovisionersResponse, error)
}

/*
ProvisionerResourceServiceList lists provisioners for a management cluster
*/
func (c *Client) ProvisionerResourceServiceList(request *provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerFullName) (*provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerListprovisionersResponse, error) {
	requestURL := helper.ConstructRequestURL(apiVersionAndGroup, request.ManagementClusterName, queryParamKeyProvisioners).String()

	response := &provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerListprovisionersResponse{}
	err := c.Get(requestURL, response)

	return response, err
}

/*
ProvisionerResourceServiceCreate creates a provisioner for a management cluster
*/
func (c *Client) ProvisionerResourceServiceCreate(request *provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerCreateProvisionerRequest) (*provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerCreateProvisionerResponse, error) {
	response := &provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerCreateProvisionerResponse{}

	requestURL := helper.ConstructRequestURL(apiVersionAndGroup, request.Provisioner.FullName.ManagementClusterName, queryParamKeyProvisioners).String()
	err := c.Create(requestURL, request, response)

	return response, err
}

/*
ProvisionerResourceServiceDelete deletes a provisioner for a management cluster
*/
func (a *Client) ProvisionerResourceServiceDelete(fn *provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerFullName) error {
	requestURL := helper.ConstructRequestURL(apiVersionAndGroup, fn.ManagementClusterName, queryParamKeyProvisioners, fn.Name).String()

	return a.Delete(requestURL)
}

/*
ProvisionerResourceServiceGet gets provisioners for a management cluster
*/
func (a *Client) ProvisionerResourceServiceGet(params *provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerFullName) (*provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerCreateProvisionerResponse, error) {
	requestURL := helper.ConstructRequestURL(apiVersionAndGroup, params.ManagementClusterName, queryParamKeyProvisioners, params.Name).String()

	response := &provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerCreateProvisionerResponse{}
	err := a.Get(requestURL, response)

	return response, err
}

/*
ProvisionerResourceServiceUpdate updates a provisioner for a management cluster
*/
func (a *Client) ProvisionerResourceServiceUpdate(request *provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerCreateProvisionerRequest) (*provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerCreateProvisionerResponse, error) {
	requestURL := helper.ConstructRequestURL(apiVersionAndGroup, request.Provisioner.FullName.ManagementClusterName, queryParamKeyProvisioners, request.Provisioner.FullName.Name).String()
	response := &provisioner.VmwareTanzuManageV1alpha1ManagementclusterProvisionerCreateProvisionerResponse{}
	err := a.Update(requestURL, request, response)

	return response, err
}
