// Code generated by go-swagger; DO NOT EDIT.

package backupscheduleclustergroupmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"

	objectmetamodel "github.com/vmware/terraform-provider-tanzu-mission-control/internal/models/objectmeta"
)

// VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSchedule A pre-scheduled or periodic Backup that should be run.
//
// swagger:model vmware.tanzu.manage.v1alpha1.clustergroup.dataprotection.schedule.Schedule
type VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSchedule struct {

	// Full name for the Schedule.
	FullName *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleFullName `json:"fullName,omitempty"`

	// Metadata for the schedule object.
	Meta *objectmetamodel.VmwareTanzuCoreV1alpha1ObjectMeta `json:"meta,omitempty"`

	// Spec for the schedule.
	Spec *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSpec `json:"spec,omitempty"`

	// Status of the schedule.
	Status *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleStatus `json:"status,omitempty"`

	// Metadata describing the type of the resource.
	Type *objectmetamodel.VmwareTanzuCoreV1alpha1ObjectType `json:"type,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSchedule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSchedule) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSchedule

	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}
