// Code generated by go-swagger; DO NOT EDIT.

package backupscheduleclustergroupmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"

	backupschedulemodel "github.com/vmware/terraform-provider-tanzu-mission-control/internal/models/backupschedule/cluster"
	batchselectormodel "github.com/vmware/terraform-provider-tanzu-mission-control/internal/models/batch_selector"
)

// VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSpec The schedule spec.
//
// swagger:model vmware.tanzu.manage.v1alpha1.clustergroup.dataprotection.schedule.Spec
type VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSpec struct {

	// Spec of the schedule defined at atomic level.
	AtomicSpec *backupschedulemodel.VmwareTanzuManageV1alpha1ClusterDataprotectionScheduleSpec `json:"atomicSpec,omitempty"`

	// Selector to include/exclude specific clusters.
	Selector *batchselectormodel.VmwareTanzuManageV1alpha1CommonBatchSelector `json:"selector,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSpec) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSpec

	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}
