// Code generated by go-swagger; DO NOT EDIT.

package backupscheduleclustergroupmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleFullName Full name of the namespace. This includes the object name along
// with any parents or further identifiers.
//
// swagger:model vmware.tanzu.manage.v1alpha1.clustergroup.dataprotection.schedule.FullName
type VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleFullName struct {

	// Name of Cluster group.
	ClusterGroupName string `json:"clusterGroupName,omitempty"`

	// Name of this Schedule.
	Name string `json:"name,omitempty"`

	// ID of Organization.
	OrgID string `json:"orgId,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleFullName) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleFullName) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleFullName

	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}

// !!! NOT GENERATED BY SWAGGER !!!.

type ListClusterGroupBackupSchedulesRequest struct {
	// Scope can be provider or cluster.
	SearchScope *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSearchScope `json:"searchScope"`

	// Sort results by.
	SortBy string `json:"sortBy,omitempty"`

	// Query to run against the API.
	Query string `json:"query,omitempty"`

	// Include Total.
	IncludeTotalCount bool `json:"includeTotal"`
}

// MarshalBinary interface implementation.
func (m *ListClusterGroupBackupSchedulesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation.
func (m *ListClusterGroupBackupSchedulesRequest) UnmarshalBinary(b []byte) error {
	var res ListClusterGroupBackupSchedulesRequest

	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}
