// Code generated by go-swagger; DO NOT EDIT.

package backupscheduleclustergroupmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleScheduleRequest Request to create a Schedule.
//
// swagger:model vmware.tanzu.manage.v1alpha1.clustergroup.dataprotection.schedule.CreateScheduleRequest
type VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleScheduleRequest struct {

	// Schedule to create.
	Schedule *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSchedule `json:"schedule,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleScheduleRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleScheduleRequest) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleScheduleRequest

	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}

// VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleScheduleResponse Response from creating a Schedule.
//
// swagger:model vmware.tanzu.manage.v1alpha1.clustergroup.dataprotection.schedule.CreateScheduleResponse
type VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleScheduleResponse struct {

	// Schedule created.
	Schedule *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSchedule `json:"schedule,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleScheduleResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleScheduleResponse) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleScheduleResponse

	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}

// VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleGetScheduleResponse Response from getting a Schedule.
//
// swagger:model vmware.tanzu.manage.v1alpha1.clustergroup.dataprotection.schedule.GetScheduleResponse
type VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleGetScheduleResponse struct {

	// Schedule returned.
	Schedule *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSchedule `json:"schedule,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleGetScheduleResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleGetScheduleResponse) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleGetScheduleResponse

	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}

// VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleListSchedulesResponse Response from listing Schedules.
//
// swagger:model vmware.tanzu.manage.v1alpha1.clustergroup.dataprotection.schedule.ListSchedulesResponse
type VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleListSchedulesResponse struct {

	// List of schedules.
	Schedules []*VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleSchedule `json:"schedules"`

	// Total count.
	TotalCount string `json:"totalCount,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleListSchedulesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleListSchedulesResponse) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ClustergroupDataprotectionScheduleListSchedulesResponse

	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}
