/*
Copyright © 2023 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
*/
// Code generated by go-swagger; DO NOT EDIT.

package managementclusterregistration

type ManagementClusterResourceServiceFullName struct {
	Name string

	OrgID string
}
