/*
Copyright © 2023 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
*/
// Code generated by go-swagger; DO NOT EDIT.

package managementclusterregistration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1ManagementclusterCreateManagementClusterRequest Request to create a ManagementCluster.
//
// swagger:model vmware.tanzu.manage.v1alpha1.managementcluster.CreateManagementClusterRequest
type VmwareTanzuManageV1alpha1ManagementclusterCreateManagementClusterRequest struct {

	// ManagementCluster to create.
	ManagementCluster *VmwareTanzuManageV1alpha1ManagementclusterManagementCluster `json:"managementCluster,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ManagementclusterCreateManagementClusterRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ManagementclusterCreateManagementClusterRequest) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ManagementclusterCreateManagementClusterRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// VmwareTanzuManageV1alpha1ManagementclusterCreateManagementClusterResponse Response from creating a ManagementCluster.
//
// swagger:model vmware.tanzu.manage.v1alpha1.managementcluster.CreateManagementClusterResponse
type VmwareTanzuManageV1alpha1ManagementclusterCreateManagementClusterResponse struct {

	// ManagementCluster created.
	ManagementCluster *VmwareTanzuManageV1alpha1ManagementclusterManagementCluster `json:"managementCluster,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ManagementclusterCreateManagementClusterResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ManagementclusterCreateManagementClusterResponse) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ManagementclusterCreateManagementClusterResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
