/*
Copyright © 2022 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
Code generated by go-swagger; DO NOT EDIT.
*/

package policyrecipeimagemodel

import "github.com/go-openapi/swag"

// VmwareTanzuManageV1alpha1CommonPolicySpecImageV1CommonRecipe is model for block-latest-tag and require-digest recipes version v1
//
// The input schema for image policy block-latest-tag and require-digest recipes.
//
// swagger:model VmwareTanzuManageV1alpha1CommonPolicySpecImageV1CommonRecipe
type VmwareTanzuManageV1alpha1CommonPolicySpecImageV1CommonRecipe struct {

	// Audit (dry-run)
	// Creates this policy for dry-run. Violations will be logged but not denied. Defaults to false (deny).
	Audit *bool `json:"audit,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1CommonPolicySpecImageV1CommonRecipe) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1CommonPolicySpecImageV1CommonRecipe) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1CommonPolicySpecImageV1CommonRecipe
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}
