---
version: "2"

run:
  build-tags:
    - akscluster
    - cluster
    - clustergroup
    - clustersecret
    - credential
    - custompolicy
    - ekscluster
    - gitrepository
    - helmfeature
    - helmrelease
    - iampolicy
    - imagepolicy
    - kustomization
    - managementcluster
    - mutationpolicy
    - namespace
    - networkpolicy
    - packageinstall
    - packagerepository
    - provisioner
    - quotapolicy
    - securitypolicy
    - sourcesecret
    - tanzupackage
    - tanzupackages
    - workspace

output:
  formats:
    text:
      path: stdout

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
  settings:
    funlen:
      lines: 150
      statements: 100
    gocognit:
      min-complexity: 60
    nestif:
      min-complexity: 14
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # TODO: Setting temporary exclusions.
      - linters:
          - dogsled
          - funlen
          - gocognit
        path: _test\.go
      - linters:
          - gosec
          - nestif
        path: internal/authctx
      - linters:
          - dupl
        path: flatten_test.go
      - linters:
          - staticcheck
        text: QF1001
      - linters:
          - staticcheck
        text: QF1003
      - linters:
          - staticcheck
        text: QF1007
      - linters:
          - staticcheck
        text: QF1011
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/vmware/terraform-provider-tanzu-mission-control
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
