# https://github.com/golangci/golangci-lint#config-file

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - goconst
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - prealloc
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl

#   don't enable:
#   - exhaustive
#   - gochecknoglobals
#   - godox
#   - gomnd
#   - goerr113
#   - gofumpt
#   - interfacer
#   - lll
#   - maligned
#   - nlreturn
#   - noctx
#   - nolintlint
#   - scopelint
#   - testpackage
#   - revive

run:
  # include test files or not, default is true
  tests: true
  deadline: 5m

linters-settings:
  funlen:
    lines: 150
    statements: 100
  nestif:
    min-complexity: 14
  gocognit:
    min-complexity: 60
  goimports:
    local-prefixes: github.com/vmware-tanzu/terraform-provider-tanzu-mission-control

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dogsled
        - funlen
        - gocognit
    - path: internal/authctx
      linters:
        - gosec
        - nestif