# © Broadcom. All Rights Reserved.
# The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.
# SPDX-License-Identifier: MPL-2.0

# For more information about the golangci-lint configuration file, refer to:
# https://golangci-lint.run/usage/configuration/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dogsled
        - funlen
        - gocognit
    - path: internal/authctx
      linters:
        - gosec
        - nestif
    - path: flatten_test.go
      linters:
        - dupl

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - prealloc
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

run:
  deadline: 5m
  build-tags:
    - akscluster
    - cluster
    - clustergroup
    - clustersecret
    - credential
    - custompolicy
    - ekscluster
    - gitrepository
    - helmfeature
    - helmrelease
    - iampolicy
    - imagepolicy
    - kustomization
    - managementcluster
    - mutationpolicy
    - namespace
    - networkpolicy
    - packageinstall
    - packagerepository
    - provisioner
    - quotapolicy
    - securitypolicy
    - sourcesecret
    - tanzupackage
    - tanzupackages
    - workspace

output:
  formats:
    - format: colored-line-number

linters-settings:
  funlen:
    lines: 150
    statements: 100
  gocognit:
    min-complexity: 60
  goimports:
    local-prefixes: github.com/vmware/terraform-provider-tanzu-mission-control
  nestif:
    min-complexity: 14
