// © Broadcom. All Rights Reserved.
// The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.
// SPDX-License-Identifier: MPL-2.0

// Code generated by go-swagger; DO NOT EDIT.

package policyrecipenetworkcommonmodel

import "github.com/go-openapi/swag"

// V1alpha1CommonPolicySpecNetworkV1Labels Label Key-Value Pair
//
// swagger:model V1alpha1CommonPolicySpecNetworkV1Labels
type V1alpha1CommonPolicySpecNetworkV1Labels struct {

	// Label Key
	// Required: true
	// Max Length: 316
	// Pattern: ^([[:alnum:]][[:alnum:]-]*[[:alnum:]](.[[:alnum:]][[:alnum:]-]*[[:alnum:]])*/)?[[:alnum:]][[:alnum:]._-]{0,61}[[:alnum:]]$
	Key string `json:"key"`

	// Label Value
	// Required: true
	// Max Length: 63
	// Pattern: ^([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$
	Value string `json:"value"`
}

// MarshalBinary interface implementation
func (m *V1alpha1CommonPolicySpecNetworkV1Labels) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1CommonPolicySpecNetworkV1Labels) UnmarshalBinary(b []byte) error {
	var res V1alpha1CommonPolicySpecNetworkV1Labels
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}
