/*
Copyright © 2023 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
*/

package inspectionsmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// VmwareTanzuManageV1alpha1ClusterInspectionScanConformanceSpec Conformance inspection scan specification.
//
// swagger:model vmware.tanzu.manage.v1alpha1.cluster.inspection.scan.ConformanceSpec
type VmwareTanzuManageV1alpha1ClusterInspectionScanConformanceSpec interface{}
