// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"

	clusterdpmodel "github.com/vmware/terraform-provider-tanzu-mission-control/internal/models/cluster/dataprotection"
	commonmodel "github.com/vmware/terraform-provider-tanzu-mission-control/internal/models/common"
)

// VmwareTanzuManageV1alpha1ClustergroupDataprotectionSpec The spec collects all the options for installing backup and restore solution into a Kubernetes cluster.
//
// swagger:model vmware.tanzu.manage.v1alpha1.clustergroup.dataprotection.Spec
type VmwareTanzuManageV1alpha1ClustergroupDataprotectionSpec struct {

	// Spec of the data protection defined at atomic level.
	AtomicSpec *clusterdpmodel.VmwareTanzuManageV1alpha1ClusterDataprotectionSpec `json:"atomicSpec,omitempty"`

	// Selector to include/exclude specific clusters (optional).
	Selector *commonmodel.VmwareTanzuManageV1alpha1CommonBatchSelector `json:"selector,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionSpec) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ClustergroupDataprotectionSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
