// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"

	commonmodel "github.com/vmware/terraform-provider-tanzu-mission-control/internal/models/common"
)

// VmwareTanzuManageV1alpha1ClustergroupDataprotectionStatus Status of the Data Protection.
//
// swagger:model vmware.tanzu.manage.v1alpha1.clustergroup.dataprotection.Status
type VmwareTanzuManageV1alpha1ClustergroupDataprotectionStatus struct {

	// Details contains information about the Cluster Group Data Protection being applied on member Clusters.
	Details *commonmodel.VmwareTanzuManageV1alpha1CommonBatchDetails `json:"details,omitempty"`

	// Generation value at the time this status was updated.
	ObservedGeneration string `json:"observedGeneration,omitempty"`

	// Phase of the Cluster Group Data Protection on member Clusters.
	Phase *commonmodel.VmwareTanzuManageV1alpha1CommonBatchPhase `json:"phase,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ClustergroupDataprotectionStatus) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ClustergroupDataprotectionStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
