// © Broadcom. All Rights Reserved.
// The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.
// SPDX-License-Identifier: MPL-2.0

package clustersourcesecret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import "github.com/go-openapi/swag"

// VmwareTanzuManageV1alpha1ClusterFluxcdSourceSecretRequest Request to create a SourceSecret.
//
// swagger:model vmware.tanzu.manage.v1alpha1.cluster.fluxcd.sourcesecret.CreateSourceSecretRequest
type VmwareTanzuManageV1alpha1ClusterFluxcdSourceSecretRequest struct {

	// SourceSecret to create.
	SourceSecret *VmwareTanzuManageV1alpha1ClusterFluxcdSourcesecret `json:"sourceSecret,omitempty"`
}

// MarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1ClusterFluxcdSourceSecretRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1ClusterFluxcdSourceSecretRequest) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ClusterFluxcdSourceSecretRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}

// VmwareTanzuManageV1alpha1ClusterFluxcdSourcesecretResponse Response from creating a SourceSecret.
//
// swagger:model vmware.tanzu.manage.v1alpha1.cluster.fluxcd.sourcesecret.CreateSourceSecretResponse
type VmwareTanzuManageV1alpha1ClusterFluxcdSourcesecretResponse struct {

	// SourceSecret created.
	SourceSecret *VmwareTanzuManageV1alpha1ClusterFluxcdSourcesecret `json:"sourceSecret,omitempty"`
}

// MarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1ClusterFluxcdSourcesecretResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1ClusterFluxcdSourcesecretResponse) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ClusterFluxcdSourcesecretResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}
