// © Broadcom. All Rights Reserved.
// The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.
// SPDX-License-Identifier: MPL-2.0

package clustersourcesecret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import "github.com/go-openapi/swag"

// VmwareTanzuManageV1alpha1ClusterFluxcdGetSourceSecretResponse Response from getting a SourceSecret.
//
// swagger:model vmware.tanzu.manage.v1alpha1.cluster.fluxcd.sourcesecret.GetSourceSecretResponse
type VmwareTanzuManageV1alpha1ClusterFluxcdGetSourceSecretResponse struct {

	// SourceSecret returned.
	SourceSecret *VmwareTanzuManageV1alpha1ClusterFluxcdSourcesecret `json:"sourceSecret,omitempty"`
}

// MarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1ClusterFluxcdGetSourceSecretResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1ClusterFluxcdGetSourceSecretResponse) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ClusterFluxcdGetSourceSecretResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}
