/*
Copyright © 2024 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
*/

package dataprotectionclient

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/url"
	"strconv"

	"github.com/vmware/terraform-provider-tanzu-mission-control/internal/client/transport"
	"github.com/vmware/terraform-provider-tanzu-mission-control/internal/helper"
	dataprotectionmodels "github.com/vmware/terraform-provider-tanzu-mission-control/internal/models/clustergroup/dataprotection"
)

const (
	apiVersionAndGroup = "v1alpha1/clustergroups"
	dataProtectionPath = "dataprotection"
)

// New creates a new data protection resource service API client.
func New(transport *transport.Client) ClientService {
	return &Client{Client: transport}
}

/*
Client for data protection resource service API.
*/
type Client struct {
	*transport.Client
}

// ClientService is the interface for Client methods.
type ClientService interface {
	DataProtectionResourceServiceCreate(request *dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionCreateDataProtectionRequest) (*dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionCreateDataProtectionResponse, error)

	DataProtectionResourceServiceDelete(fn *dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionFullName, deleteBackups bool, force bool) error

	DataProtectionResourceServiceList(fn *dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionFullName) (*dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionListDataProtectionsResponse, error)

	DataProtectionResourceServiceUpdate(request *dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionCreateDataProtectionRequest) (*dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionCreateDataProtectionResponse, error)
}

/*
DataProtectionResourceServiceCreate enables data protection on a cluster.
*/
func (c *Client) DataProtectionResourceServiceCreate(request *dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionCreateDataProtectionRequest,
) (*dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionCreateDataProtectionResponse, error) {
	response := &dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionCreateDataProtectionResponse{}
	requestURL := helper.ConstructRequestURL(apiVersionAndGroup, request.DataProtection.FullName.ClusterGroupName, dataProtectionPath).String()
	err := c.Create(requestURL, request, response)

	return response, err
}

/*
DataProtectionResourceServiceDelete disables data protection on a cluster.
*/
func (c *Client) DataProtectionResourceServiceDelete(fn *dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionFullName, deleteBackups bool, force bool) error {
	requestURL := helper.ConstructRequestURL(apiVersionAndGroup, fn.ClusterGroupName, dataProtectionPath)
	queryParams := url.Values{}

	if force {
		queryParams.Add("force", strconv.FormatBool(force))
	}

	if deleteBackups {
		queryParams.Add("deleteBackups", strconv.FormatBool(deleteBackups))
	}

	requestURL = requestURL.AppendQueryParams(queryParams)

	return c.Delete(requestURL.String())
}

/*
DataProtectionResourceServiceList gets data protection details.
*/
func (c *Client) DataProtectionResourceServiceList(fn *dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionFullName,
) (*dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionListDataProtectionsResponse, error) {
	requestURL := helper.ConstructRequestURL(apiVersionAndGroup, fn.ClusterGroupName, dataProtectionPath)
	queryParams := url.Values{}

	if len(queryParams) > 0 {
		requestURL = requestURL.AppendQueryParams(queryParams)
	}

	resp := &dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionListDataProtectionsResponse{}
	err := c.Get(requestURL.String(), resp)

	return resp, err
}

/*
DataProtectionResourceServiceUpdate updates a data protection configuration on a cluster.
*/
func (c *Client) DataProtectionResourceServiceUpdate(request *dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionCreateDataProtectionRequest,
) (*dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionCreateDataProtectionResponse, error) {
	response := &dataprotectionmodels.VmwareTanzuManageV1alpha1ClustergroupDataprotectionCreateDataProtectionResponse{}
	requestURL := helper.ConstructRequestURL(apiVersionAndGroup, request.DataProtection.FullName.ClusterGroupName, dataProtectionPath).String()
	err := c.Update(requestURL, request, response)

	return response, err
}
