/*
Copyright © 2024 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
*/

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1CommonBatchSelector Selector to include/exclude specific targets.
//
// swagger:model vmware.tanzu.manage.v1alpha1.common.batch.Selector
type VmwareTanzuManageV1alpha1CommonBatchSelector struct {

	// List of target names to exclude.
	ExcludedNames []string `json:"excludedNames"`

	// Label based Selector.
	LabelSelector *VmwareTanzuManageV1alpha1CommonBatchLabelSelector `json:"labelSelector,omitempty"`

	// List of target names to include.
	Names []string `json:"names"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1CommonBatchSelector) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1CommonBatchSelector) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1CommonBatchSelector
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
