// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1CommonBatchLabelSelector Label Selector.
//
// swagger:model vmware.tanzu.manage.v1alpha1.common.batch.LabelSelector
type VmwareTanzuManageV1alpha1CommonBatchLabelSelector struct {

	// Match expressions is a list of label selector requirements, the requirements are ANDed.
	// Label selector requirements support 4 operators for matching labels - in, notin, exists and doesnotexist.
	MatchExpressions []*K8sIoApimachineryPkgApisMetaV1LabelSelectorRequirement `json:"matchExpressions"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1CommonBatchLabelSelector) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1CommonBatchLabelSelector) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1CommonBatchLabelSelector
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
