/*
Copyright © 2022 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
*/
// Code generated by go-swagger; DO NOT EDIT.

package credentialmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1AccountCredentialTypeAwsSpec AWS credential spec.
//
// swagger:model vmware.tanzu.manage.v1alpha1.account.credential.type.aws.Spec
type VmwareTanzuManageV1alpha1AccountCredentialTypeAwsSpec struct {

	// AWS access key ID and secret access key.
	AccessKey *VmwareTanzuManageV1alpha1AccountCredentialTypeAwsAccessKey `json:"accessKey,omitempty"`

	// Account ID of the AWS credential.
	AccountID string `json:"accountId,omitempty"`

	// Generic credential.
	GenericCredential string `json:"genericCredential,omitempty"`

	// AWS IAM role ARN and external ID.
	IamRole *VmwareTanzuManageV1alpha1AccountCredentialTypeAwsIAMRole `json:"iamRole,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialTypeAwsSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialTypeAwsSpec) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1AccountCredentialTypeAwsSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// VmwareTanzuManageV1alpha1AccountCredentialTypeAwsAccessKey AWS access key ID and secret access key pair.
//
// swagger:model vmware.tanzu.manage.v1alpha1.account.credential.type.aws.AccessKey
type VmwareTanzuManageV1alpha1AccountCredentialTypeAwsAccessKey struct {

	// AWS access key ID.
	AccessKeyID string `json:"accessKeyId,omitempty"`

	// Secret access key for the access key ID.
	SecretAccessKey string `json:"secretAccessKey,omitempty"`
}

// VmwareTanzuManageV1alpha1AccountCredentialTypeAwsIAMRole AWS IAM role ARN and external ID.
//
// swagger:model vmware.tanzu.manage.v1alpha1.account.credential.type.aws.IAMRole
type VmwareTanzuManageV1alpha1AccountCredentialTypeAwsIAMRole struct {

	// AWS IAM role ARN.
	Arn string `json:"arn,omitempty"`

	// An external ID used to assume an AWS IAM role.
	ExtID string `json:"extId,omitempty"`
}
