// © Broadcom. All Rights Reserved.
// The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.
// SPDX-License-Identifier: MPL-2.0

// Code generated by go-swagger; DO NOT EDIT.

package credentialmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1AccountCredentialTypeAzureSpec Azure credential spec.
//
// swagger:model vmware.tanzu.manage.v1alpha1.account.credential.type.azure.Spec
type VmwareTanzuManageV1alpha1AccountCredentialTypeAzureSpec struct {

	// Service Principal.
	ServicePrincipal *VmwareTanzuManageV1alpha1AccountCredentialTypeAzureServicePrincipal `json:"servicePrincipal,omitempty"`

	// ServicePrincipalWithCertificate.
	ServicePrincipalWithCertificate *VmwareTanzuManageV1alpha1AccountCredentialTypeAzureServicePrincipalWithCertificate `json:"servicePrincipalWithCertificate,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialTypeAzureSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialTypeAzureSpec) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1AccountCredentialTypeAzureSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
