/*
Copyright © 2023 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
*/
// Code generated by go-swagger; DO NOT EDIT.

// Code generated by go-swagger; DO NOT EDIT.

package credentialmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1AccountCredentialTypeAzureServicePrincipal Azure Service Principal.
//
// swagger:model vmware.tanzu.manage.v1alpha1.account.credential.type.azure.ServicePrincipal
type VmwareTanzuManageV1alpha1AccountCredentialTypeAzureServicePrincipal struct {

	// Azure Cloud name.
	AzureCloudName string `json:"azureCloudName,omitempty"`

	// Client ID of the Service Principal.
	ClientID string `json:"clientId,omitempty"`

	// Client Secret of the Service Principal.
	ClientSecret string `json:"clientSecret,omitempty"`

	// Resource Group name.
	ResourceGroup string `json:"resourceGroup,omitempty"`

	// Subscription ID of the Azure credential.
	SubscriptionID string `json:"subscriptionId,omitempty"`

	// Tenant ID of the Azure credential.
	TenantID string `json:"tenantId,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialTypeAzureServicePrincipal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialTypeAzureServicePrincipal) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1AccountCredentialTypeAzureServicePrincipal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
