// © Broadcom. All Rights Reserved.
// The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.
// SPDX-License-Identifier: MPL-2.0

// Code generated by go-swagger; DO NOT EDIT.

package credentialmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	objectmetamodel "github.com/vmware/terraform-provider-tanzu-mission-control/internal/models/objectmeta"

	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1AccountCredentialCredential A credential for an infrastructure provider account connection.
//
// Credentials are scoped to and used by Tanzu Mission Control services to operate
// on resources in an infrastructure provider. The credential data is always encrypted
// and securely stored.
//
// swagger:model vmware.tanzu.manage.v1alpha1.account.credential.Credential
type VmwareTanzuManageV1alpha1AccountCredentialCredential struct {

	// Full name for the credential.
	FullName *VmwareTanzuManageV1alpha1AccountCredentialFullName `json:"fullName,omitempty"`

	// Metadata for the credential object.
	Meta *objectmetamodel.VmwareTanzuCoreV1alpha1ObjectMeta `json:"meta,omitempty"`

	// Spec for the credential.
	Spec *VmwareTanzuManageV1alpha1AccountCredentialSpec `json:"spec,omitempty"`

	// Status for the credential.
	Status *VmwareTanzuManageV1alpha1AccountCredentialStatus `json:"status,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialCredential) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialCredential) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1AccountCredentialCredential
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// VmwareTanzuManageV1alpha1AccountCredentialFullName Full name of the credential. This includes the object name along
// with any parents or further identifiers.
//
// swagger:model vmware.tanzu.manage.v1alpha1.account.credential.FullName
type VmwareTanzuManageV1alpha1AccountCredentialFullName struct {

	// Name of this credential.
	Name string `json:"name,omitempty"`

	// ID of Organization.
	OrgID string `json:"orgId,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialFullName) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialFullName) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1AccountCredentialFullName
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
