// © Broadcom. All Rights Reserved.
// The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.
// SPDX-License-Identifier: MPL-2.0

// Code generated by go-swagger; DO NOT EDIT.

package credentialmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1AccountCredentialCreateCredentialRequest Request to create a Credential.
//
// swagger:model vmware.tanzu.manage.v1alpha1.account.credential.CreateCredentialRequest
type VmwareTanzuManageV1alpha1AccountCredentialCreateCredentialRequest struct {

	// Credential to create.
	Credential *VmwareTanzuManageV1alpha1AccountCredentialCredential `json:"credential,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialCreateCredentialRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialCreateCredentialRequest) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1AccountCredentialCreateCredentialRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// VmwareTanzuManageV1alpha1AccountCredentialCreateCredentialResponse Response from creating a Credential.
//
// swagger:model vmware.tanzu.manage.v1alpha1.account.credential.CreateCredentialResponse
type VmwareTanzuManageV1alpha1AccountCredentialCreateCredentialResponse struct {

	// Credential created.
	Credential *VmwareTanzuManageV1alpha1AccountCredentialCredential `json:"credential,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialCreateCredentialResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialCreateCredentialResponse) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1AccountCredentialCreateCredentialResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// VmwareTanzuManageV1alpha1AccountCredentialGetCredentialResponse Response from getting a Credential.
//
// swagger:model vmware.tanzu.manage.v1alpha1.account.credential.GetCredentialResponse
type VmwareTanzuManageV1alpha1AccountCredentialGetCredentialResponse struct {

	// Credential returned.
	Credential *VmwareTanzuManageV1alpha1AccountCredentialCredential `json:"credential,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialGetCredentialResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1AccountCredentialGetCredentialResponse) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1AccountCredentialGetCredentialResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
