/*
Copyright © 2023 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
Code generated by go-swagger; DO NOT EDIT.
*/

package policyrecipenetworkmodel

import "github.com/go-openapi/swag"

// V1alpha1CommonPolicySpecNetworkV1AllowAll allow-all schema
//
// swagger:model V1alpha1CommonPolicySpecNetworkV1AllowAll
type V1alpha1CommonPolicySpecNetworkV1AllowAll struct {

	// Allow traffic only from own namespace
	// Allow traffic only from pods in the same namespace as the destination pod. Defaults to false (allow from all namespaces).
	FromOwnNamespace *bool `json:"fromOwnNamespace,omitempty"`
}

// MarshalBinary interface implementation
func (m *V1alpha1CommonPolicySpecNetworkV1AllowAll) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1CommonPolicySpecNetworkV1AllowAll) UnmarshalBinary(b []byte) error {
	var res V1alpha1CommonPolicySpecNetworkV1AllowAll
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}
