// © Broadcom. All Rights Reserved.
// The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.
// SPDX-License-Identifier: MPL-2.0

// Code generated by go-swagger; DO NOT EDIT.

package policyrecipecustommodel

import (
	"github.com/go-openapi/swag"

	policyrecipecustomcommonmodel "github.com/vmware/terraform-provider-tanzu-mission-control/internal/models/policy/recipe/custom/common"
)

// VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabels tmc-require-labels recipe schema.
//
// The input schema for tmc-require-labels recipe.
//
// swagger:model VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabels
type VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabels struct {

	// Audit (dry-run).
	// Creates this policy for dry-run. Violations will be logged but not denied. Defaults to false (deny).
	Audit bool `json:"audit,omitempty"`

	// Parameters.
	Parameters *VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabelsParameters `json:"parameters,omitempty"`

	// TargetKubernetesResources is a list of kubernetes api resources on which the policy will be enforced, identified using apiGroups and kinds. You can use 'kubectl api-resources' to view the list of available api resources on your cluster.
	// Required: true
	// Min Items: 1
	TargetKubernetesResources []*policyrecipecustomcommonmodel.VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TargetKubernetesResources `json:"targetKubernetesResources"`
}

// MarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabels) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabels) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabels
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}

// VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabelsParameters Parameters.
//
// swagger:model VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabelsParameters
type VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabelsParameters struct {

	// Labels.
	// Min Items: 1
	Labels []*VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabelsParametersLabels `json:"labels"`
}

// MarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabelsParameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabelsParameters) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabelsParameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}

// VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabelsParametersLabels Labels.
//
// swagger:model VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabelsParametersLabels
type VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabelsParametersLabels struct {

	// The label key to enforce.
	Key string `json:"key,omitempty"`

	// Optional label value to enforce (if left empty, only key will be enforced).
	Value string `json:"value,omitempty"`
}

// MarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabelsParametersLabels) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabelsParametersLabels) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1CommonPolicySpecCustomV1TMCRequireLabelsParametersLabels
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}
