/*
Copyright © 2022 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
*/

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"

	objectmetamodel "github.com/vmware/terraform-provider-tanzu-mission-control/internal/models/objectmeta"
)

// VmwareTanzuManageV1alpha1EksclusterEksCluster EksCluster is an EKS Kubernetes Cluster.
//
// swagger:model vmware.tanzu.manage.v1alpha1.ekscluster.EksCluster
type VmwareTanzuManageV1alpha1EksclusterEksCluster struct {

	// Full name for the cluster.
	FullName *VmwareTanzuManageV1alpha1EksclusterFullName `json:"fullName,omitempty"`

	// Metadata for the cluster object.
	Meta *objectmetamodel.VmwareTanzuCoreV1alpha1ObjectMeta `json:"meta,omitempty"`

	// Spec for the cluster.
	Spec *VmwareTanzuManageV1alpha1EksclusterSpec `json:"spec,omitempty"`

	// Status for the cluster.
	Status *VmwareTanzuManageV1alpha1EksclusterStatus `json:"status,omitempty"`

	// Metadata describing the type of the resource.
	Type *objectmetamodel.VmwareTanzuCoreV1alpha1ObjectType `json:"type,omitempty"`
}

// MarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1EksclusterEksCluster) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1EksclusterEksCluster) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1EksclusterEksCluster
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}
