// © Broadcom. All Rights Reserved.
// The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.
// SPDX-License-Identifier: MPL-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1EksclusterKubernetesNetworkConfig The network configuration for the EKS cluster.
//
// swagger:model vmware.tanzu.manage.v1alpha1.ekscluster.KubernetesNetworkConfig
type VmwareTanzuManageV1alpha1EksclusterKubernetesNetworkConfig struct {

	// Service CIDR for Kubernetes services.
	ServiceCidr string `json:"serviceCidr,omitempty"`
}

// MarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1EksclusterKubernetesNetworkConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1EksclusterKubernetesNetworkConfig) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1EksclusterKubernetesNetworkConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}
