/*
Copyright 2022 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
*/

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1EksclusterKubernetesNetworkConfig The network configuration for the EKS cluster.
//
// swagger:model vmware.tanzu.manage.v1alpha1.ekscluster.KubernetesNetworkConfig
type VmwareTanzuManageV1alpha1EksclusterKubernetesNetworkConfig struct {

	// Service CIDR for Kubernetes services.
	ServiceCidr string `json:"serviceCidr,omitempty"`
}

// Validate validates this vmware tanzu manage v1alpha1 ekscluster kubernetes network config
func (m *VmwareTanzuManageV1alpha1EksclusterKubernetesNetworkConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vmware tanzu manage v1alpha1 ekscluster kubernetes network config based on context it is used
func (m *VmwareTanzuManageV1alpha1EksclusterKubernetesNetworkConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1EksclusterKubernetesNetworkConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1EksclusterKubernetesNetworkConfig) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1EksclusterKubernetesNetworkConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
