// © Broadcom. All Rights Reserved.
// The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.
// SPDX-License-Identifier: MPL-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1EksclusterNodepoolLaunchTemplate Launch template for the nodepool.
//
// swagger:model vmware.tanzu.manage.v1alpha1.ekscluster.nodepool.LaunchTemplate
type VmwareTanzuManageV1alpha1EksclusterNodepoolLaunchTemplate struct {

	// The ID of the launch template.
	ID string `json:"id,omitempty"`

	// The name of the launch template.
	Name string `json:"name,omitempty"`

	// The version of the launch template to use. If no version is specified, then the template's default version is used.
	Version string `json:"version,omitempty"`
}

// MarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1EksclusterNodepoolLaunchTemplate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1EksclusterNodepoolLaunchTemplate) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1EksclusterNodepoolLaunchTemplate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}
