/*
Copyright 2022 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
*/

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1EksclusterNodepoolInfo Info is the meta information of nodepool for cluster.
//
// swagger:model vmware.tanzu.manage.v1alpha1.ekscluster.nodepool.Info
type VmwareTanzuManageV1alpha1EksclusterNodepoolInfo struct {

	// Description for the nodepool.
	Description string `json:"description,omitempty"`

	// Name of the nodepool.
	Name string `json:"name,omitempty"`
}

// Validate validates this vmware tanzu manage v1alpha1 ekscluster nodepool info
func (m *VmwareTanzuManageV1alpha1EksclusterNodepoolInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vmware tanzu manage v1alpha1 ekscluster nodepool info based on context it is used
func (m *VmwareTanzuManageV1alpha1EksclusterNodepoolInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1EksclusterNodepoolInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1EksclusterNodepoolInfo) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1EksclusterNodepoolInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
