/*
Copyright 2022 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
*/

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1EksclusterNodepoolRemoteAccess Remote access to worker nodes.
//
// swagger:model vmware.tanzu.manage.v1alpha1.ekscluster.nodepool.RemoteAccess
type VmwareTanzuManageV1alpha1EksclusterNodepoolRemoteAccess struct {

	// Security groups for the cluster VMs.
	SecurityGroups []string `json:"securityGroups"`

	// SSH key for the nodepool VMs.
	SSHKey string `json:"sshKey,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1EksclusterNodepoolRemoteAccess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1EksclusterNodepoolRemoteAccess) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1EksclusterNodepoolRemoteAccess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
