// © Broadcom. All Rights Reserved.
// The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.
// SPDX-License-Identifier: MPL-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1EksclusterVPCConfig The VPC configuration for the EKS cluster.
//
// swagger:model vmware.tanzu.manage.v1alpha1.ekscluster.VPCConfig
type VmwareTanzuManageV1alpha1EksclusterVPCConfig struct {

	// Enable private access on the cluster.
	EnablePrivateAccess bool `json:"enablePrivateAccess,omitempty"`

	// Enable public access on the cluster.
	EnablePublicAccess bool `json:"enablePublicAccess,omitempty"`

	// Public access cidrs.
	PublicAccessCidrs []string `json:"publicAccessCidrs"`

	// Security groups for the cluster VMs.
	SecurityGroups []string `json:"securityGroups"`

	// Subnet ids used by the cluster.
	SubnetIds []string `json:"subnetIds"`
}

// MarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1EksclusterVPCConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1EksclusterVPCConfig) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1EksclusterVPCConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}

	*m = res

	return nil
}
