/*
Copyright © 2023 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
*/
// Code generated by go-swagger; DO NOT EDIT.

package managementclustermodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"

	objectmetamodel "github.com/vmware/terraform-provider-tanzu-mission-control/internal/models/objectmeta"
)

// VmwareTanzuManageV1alpha1ManagementclusterManagementCluster A ManagementCluster maintains the connection between a Tanzu Kubernetes Grid instance and the platform.
//
// swagger:model vmware.tanzu.manage.v1alpha1.managementcluster.ManagementCluster
type VmwareTanzuManageV1alpha1ManagementclusterManagementCluster struct {

	// Full name for the ManagementCluster.
	FullName *VmwareTanzuManageV1alpha1ManagementclusterFullName `json:"fullName,omitempty"`

	// Metadata for the ManagementCluster object.
	//Meta *VmwareTanzuCoreV1alpha1ObjectMeta `json:"meta,omitempty"`
	Meta *objectmetamodel.VmwareTanzuCoreV1alpha1ObjectMeta `json:"meta,omitempty"`

	// Spec for the ManagementCluster.
	Spec *VmwareTanzuManageV1alpha1ManagementclusterSpec `json:"spec,omitempty"`

	// Status of the ManagementCluster.
	Status *VmwareTanzuManageV1alpha1ManagementclusterStatus `json:"status,omitempty"`

	// Metadata describing the type of the resource.
	//Type *VmwareTanzuCoreV1alpha1ObjectType `json:"type,omitempty"`
	Type *objectmetamodel.VmwareTanzuCoreV1alpha1ObjectType `json:"type,omitempty"`
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ManagementclusterManagementCluster) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ManagementclusterManagementCluster) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ManagementclusterManagementCluster
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
