/*
Copyright © 2023 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
*/
// Code generated by go-swagger; DO NOT EDIT.

package managementclustermodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VmwareTanzuManageV1alpha1ManagementclusterManagementClusterGetManifestResponse The response type for getting the registration manifest
// for a management cluster.
//
// swagger:model vmware.tanzu.manage.v1alpha1.managementcluster.ManagementClusterGetManifestResponse
type VmwareTanzuManageV1alpha1ManagementclusterManagementClusterGetManifestResponse struct {

	// Registration manifest for the management cluster resource.
	Manifest string `json:"manifest,omitempty"`
}

// Validate validates this vmware tanzu manage v1alpha1 managementcluster management cluster get manifest response
func (m *VmwareTanzuManageV1alpha1ManagementclusterManagementClusterGetManifestResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vmware tanzu manage v1alpha1 managementcluster management cluster get manifest response based on context it is used
func (m *VmwareTanzuManageV1alpha1ManagementclusterManagementClusterGetManifestResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ManagementclusterManagementClusterGetManifestResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VmwareTanzuManageV1alpha1ManagementclusterManagementClusterGetManifestResponse) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ManagementclusterManagementClusterGetManifestResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
