// Code generated by go-swagger; DO NOT EDIT.

package clustergroupsourcesecret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import "github.com/go-openapi/swag"

// VmwareTanzuManageV1alpha1ClustergroupFluxcdGetSourceSecretResponse Response from getting a SourceSecret.
//
// swagger:model vmware.tanzu.manage.v1alpha1.clustergroup.fluxcd.sourcesecret.GetSourceSecretResponse
type VmwareTanzuManageV1alpha1ClustergroupFluxcdGetSourceSecretResponse struct {

	// SourceSecret returned.
	SourceSecret *VmwareTanzuManageV1alpha1ClustergroupFluxcdSourcesecretSourceSecret `json:"sourceSecret,omitempty"`
}

// MarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1ClustergroupFluxcdGetSourceSecretResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation.
func (m *VmwareTanzuManageV1alpha1ClustergroupFluxcdGetSourceSecretResponse) UnmarshalBinary(b []byte) error {
	var res VmwareTanzuManageV1alpha1ClustergroupFluxcdGetSourceSecretResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
