/*
Copyright © 2023 VMware, Inc. All Rights Reserved.
SPDX-License-Identifier: MPL-2.0
*/

package tkcnodepool

// VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase Phase of the nodepool resource.
//
//   - PHASE_UNSPECIFIED: Unspecified phase.
//   - CREATING: Resource is pending processing.
//   - READY: Resource is in ready state.
//   - ERROR: Error in processing.
//   - DELETING: Resource is being deleted.
//   - RESIZING: Resizing state.
//   - UPGRADING: An upgrade is in progress.
//   - UPGRADE_FAILED: An upgrade has failed.
//   - WAITING: The cluster is not created yet. so wait till then.
//   - UPDATING: A generic phase for nodepool update.
//
// swagger:model vmware.tanzu.manage.v1alpha1.managementcluster.provisioner.tanzukubernetescluster.nodepool.Status.Phase
type VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase string

func NewVmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase(value VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase) *VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase {
	return &value
}

// Pointer returns a pointer to a freshly-allocated VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase.
func (m VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase) Pointer() *VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase {
	return &m
}

const (

	// VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhasePHASEUNSPECIFIED captures enum value "PHASE_UNSPECIFIED".
	VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhasePHASEUNSPECIFIED VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase = "PHASE_UNSPECIFIED"

	// VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseCREATING captures enum value "CREATING".
	VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseCREATING VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase = "CREATING"

	// VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseREADY captures enum value "READY".
	VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseREADY VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase = "READY"

	// VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseERROR captures enum value "ERROR".
	VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseERROR VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase = "ERROR"

	// VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseDELETING captures enum value "DELETING".
	VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseDELETING VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase = "DELETING"

	// VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseRESIZING captures enum value "RESIZING".
	VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseRESIZING VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase = "RESIZING"

	// VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseUPGRADING captures enum value "UPGRADING".
	VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseUPGRADING VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase = "UPGRADING"

	// VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseUPGRADEFAILED captures enum value "UPGRADE_FAILED".
	VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseUPGRADEFAILED VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase = "UPGRADE_FAILED"

	// VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseWAITING captures enum value "WAITING".
	VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseWAITING VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase = "WAITING"

	// VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseUPDATING captures enum value "UPDATING".
	VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhaseUPDATING VmwareTanzuManageV1alpha1ManagementclusterProvisionerTanzukubernetesclusterNodepoolStatusPhase = "UPDATING"
)
