---
name: Pull Request Labels

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review

permissions:
  contents: read

jobs:
  label-pull-requests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Apply Labels
        uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6.2.0
        with:
          configuration-path: .github/labeler-pull-requests.yml
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
